from app.agents.state import ActionItem
from app.integrations.base import BaseIntegration
from app.integrations.registry import IntegrationRegistry


@IntegrationRegistry.register("github")
class GitHubIntegration(BaseIntegration):
    async def create_task(self, item: ActionItem) -> dict:
        payload = {
            "title": item["title"],
            "body": self._build_body(item),
            "assignees": [await self._resolve_github_user(item["owner_email"])],
            "labels": ["meeting-action", f"priority:{item['priority']}"],
            "milestone": await self._find_milestone(item["due_date_resolved"]),
        }
        response = await self.client.post(
            f"/repos/{self.config['repo']}/issues", json=payload
        )
        return {"external_id": str(response["number"]), "external_url": response["html_url"]}

    def _build_body(self, item: ActionItem) -> str:
        return (
            f"Generated by MeetMind from meeting: {item.get('meeting_id')}\n\n"
            f"{item['description']}\n\n"
            f"Evidence: {item['evidence_quote']}\n"
            f"Confidence: {item['confidence_score'] * 100:.0f}%"
        )

    async def _resolve_github_user(self, email: str) -> str:
        raise NotImplementedError("TODO: look up the GitHub username for this email")

    async def _find_milestone(self, due_date: str):
        raise NotImplementedError("TODO: map a due date to a milestone, or return None")

    @property
    def client(self):
        raise NotImplementedError("TODO: wire up an authenticated GitHub HTTP client")
