"""GitHub Issues integration."""
import httpx
from app.integrations.base import BaseIntegration, IntegrationResult
from app.config import settings

LABEL_MAP = {"critical": "priority: critical", "high": "priority: high",
             "medium": "priority: medium", "low": "priority: low"}


class GitHubIntegration(BaseIntegration):
    name = "github"

    async def check_existing(self, fingerprint: str, config: dict) -> str | None:
        token = config.get("token", settings.github_token)
        repo = config.get("repo", settings.github_repo)
        async with httpx.AsyncClient() as client:
            resp = await client.get(
                f"https://api.github.com/repos/{repo}/issues",
                params={"labels": f"meetmind-{fingerprint}", "state": "open"},
                headers={"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"},
            )
            if resp.status_code == 200 and resp.json():
                return str(resp.json()[0]["number"])
        return None

    async def create_task(self, item, config: dict) -> IntegrationResult:
        token = config.get("token", settings.github_token)
        repo = config.get("repo", settings.github_repo)

        if not token or not repo:
            return IntegrationResult(success=False, error="GitHub not configured.")

        existing = await self.check_existing(item.fingerprint, config)
        if existing:
            return IntegrationResult(success=True, external_id=existing,
                                     external_url=f"https://github.com/{repo}/issues/{existing}",
                                     error="Duplicate — returned existing issue")

        body = (
            f"## Description\n{item.description}\n\n"
            f"## Evidence\n> {item.evidence_quote}\n"
            f"*Timestamp: {item.evidence_timestamp}*\n\n"
            f"**Owner:** {item.owner_resolved.resolved_name if item.owner_resolved else item.owner_raw}\n"
            f"**Due:** {item.due_date_resolved or item.due_date_raw or 'TBD'}\n"
            f"**Confidence:** {item.confidence:.0%}\n\n"
            f"*Generated by MeetMind AI*"
        )

        payload = {
            "title": item.title,
            "body": body,
            "labels": ["meetmind", f"meetmind-{item.fingerprint}", LABEL_MAP.get(item.priority, "priority: medium")],
        }

        if item.owner_resolved and item.owner_resolved.resolved_name:
            payload["assignees"] = [item.owner_resolved.resolved_name.lower().replace(" ", "")]

        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"https://api.github.com/repos/{repo}/issues",
                json=payload,
                headers={"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"},
            )

        if resp.status_code == 201:
            data = resp.json()
            return IntegrationResult(
                success=True,
                external_id=str(data["number"]),
                external_url=data["html_url"],
                payload_sent=payload,
                response={"number": data["number"], "url": data["html_url"]},
            )
        return IntegrationResult(success=False, error=f"GitHub API {resp.status_code}: {resp.text[:200]}")
