from app.agents.state import ActionItem
from app.integrations.base import BaseIntegration
from app.integrations.registry import IntegrationRegistry


@IntegrationRegistry.register("jira")
class JiraIntegration(BaseIntegration):
    async def create_task(self, item: ActionItem) -> dict:
        payload = {
            "fields": {
                "project": {"key": self.config["project_key"]},
                "summary": item["title"],
                "description": self._build_description(item),
                "issuetype": {"name": "Task"},
                "assignee": {"accountId": await self._resolve_jira_user(item["owner_email"])},
                "priority": {"name": self._map_priority(item["priority"])},
                "duedate": item["due_date_resolved"],
                "labels": ["meetmind-generated"],
                "customfield_meeting_id": item.get("meeting_id"),
            }
        }
        response = await self.client.post("/rest/api/3/issue", json=payload)
        return {
            "external_id": response["key"],
            "external_url": f"{self.base_url}/browse/{response['key']}",
        }

    def _build_description(self, item: ActionItem) -> str:
        return f"""
*Generated by MeetMind from meeting: {item.get('meeting_id')}*

{item['description']}

---
*Evidence:* _{item['evidence_quote']}_
*Timestamp:* {item['evidence_timestamp']}s
*Confidence:* {item['confidence_score'] * 100:.0f}%
*Dependencies:* {', '.join(item.get('dependencies', []))}
        """

    async def _resolve_jira_user(self, email: str) -> str:
        raise NotImplementedError("TODO: look up the Jira accountId for this email")

    def _map_priority(self, priority: str) -> str:
        return {"high": "High", "medium": "Medium", "low": "Low"}.get(priority, "Medium")

    @property
    def client(self):
        raise NotImplementedError("TODO: wire up an authenticated Jira HTTP client")

    @property
    def base_url(self) -> str:
        return self.config.get("base_url", "")
